# Generated by Django 5.2.3 on 2025-06-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Subject of the message', max_length=200, null=True)),
                ('message', models.TextField(help_text='Content of the message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time the message was received')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates if the message has been read by an admin')),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the service (e.g., 'Web Development')", max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome or other icon class (e.g., 'fas fa-code')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which services should appear')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the technology (e.g., 'Python', 'React')", max_length=50, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome or other icon class for the technology', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=200)),
                ('short_description', models.CharField(blank=True, help_text='A brief summary of the project', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('project_url', models.URLField(blank=True, help_text='URL to the live project (optional)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image representing the project', null=True, upload_to='projects/')),
                ('date_completed', models.DateField(blank=True, help_text='Date the project was completed', null=True)),
                ('technologies', models.ManyToManyField(help_text='Technologies used in this project', related_name='projects', to='website.technology')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_completed', 'title'],
            },
        ),
    ]
