# Generated by Django 5.2.3 on 2025-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the tag (e.g., 'Python', 'AI', 'Frontend')", max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly version of the tag name (auto-generated)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check to feature this service on the homepage or dedicated section.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this blog post.', related_name='blogposts', to='website.tag'),
        ),
    ]
