# Generated by Django 5.2.3 on 2025-06-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tag_service_is_featured_blogpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person leaving the comment.', max_length=100)),
                ('author_email', models.EmailField(blank=True, help_text='Email of the person leaving the comment (optional).', max_length=254, null=True)),
                ('comment_text', models.TextField(help_text='The content of the comment.')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Date and time the comment was published.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the comment has been approved for display.')),
                ('blog_post', models.ForeignKey(help_text='The blog post this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['pub_date'],
            },
        ),
    ]
