# Generated by Django 5.2.3 on 2025-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="The subscriber's email address.", max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True, help_text='Date and time of subscription.')),
            ],
            options={
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-date_subscribed'],
            },
        ),
    ]
